version: '3'
services:
  dev:
    container_name: mc.dev
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    ports:
      - '3000'
      - '25565'
      - '8123'
    environment:
      HOST: 0.0.0.0
    volumes:
      - ./:/workspace
    command: sleep infinity
